### ISSUE TITLE
not rails 3.1 compatible

### ISSUE THREAD

**Issue by gucki** [zdenal/url_validator#1]
I guess you'd only have to losen the rails dependecy in the gemspec. The validators api didnt change as far as I know.

**Comment by gucki** [comment]
This fork https://github.com/DanThiffault/url_validator seems to have some pretty good enhancements. Would you mind to pull them? :)

**Comment by zdenal** [comment]
Hi gucki, rails dependency in the gempsec is removed. Thanks for your feedback.

About fork what you recommended - I miss there some requirements as automated push preferred schema to attributes and tests are also broken. So I have to check that more and see what I can reuse.

Cheers ;)
